name: Python Build and Test

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'
    - name: Install linters
      run: |
        python -m pip install --upgrade pip
        pip install flake8 black isort
    - name: Run linters
      run: |
        isort --check --diff src/qcxms/
        black --check --diff src/qcxms/
        flake8 src/qcxms/

  test:
    runs-on: ubuntu-latest
    needs: lint # Ensure linting passes before testing
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11']
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e . # Install project in editable mode with dependencies
        pip install pytest # Install pytest
    - name: Run tests (placeholder)
      run: |
        pytest tests/ 
        # This will currently find no tests if the /tests directory is empty 
        # or does not contain pytest-discoverable tests.
        # Add '|| true' to not fail the job if no tests are found initially:
        # pytest tests/ || true

  build:
    runs-on: ubuntu-latest
    needs: test # Ensure tests pass before building
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'
    - name: Install build tools
      run: |
        python -m pip install --upgrade pip
        pip install build
    - name: Build package
      run: python -m build
    - name: List build artifacts
      run: ls -lh dist/
```
